/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedStaffCategoriesRouteImport } from './routes/_authenticated/staff.categories'
import { Route as AuthenticatedStaffCustomersRouteImport } from './routes/_authenticated/staff.customers'
import { Route as AuthenticatedStaffImportRouteImport } from './routes/_authenticated/staff.import'
import { Route as AuthenticatedStaffInvitesRouteImport } from './routes/_authenticated/staff.invites'
import { Route as AuthenticatedStaffProductsRouteImport } from './routes/_authenticated/staff.products'
import { Route as AuthenticatedStaffSettingsRouteImport } from './routes/_authenticated/staff.settings'
import { Route as AuthenticatedStaffOrdersOrderIdRouteImport } from './routes/_authenticated/staff.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffCategoriesRoute =
  AuthenticatedStaffCategoriesRouteImport.update({
    id: '/staff/categories',
    path: '/staff/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffCustomersRoute =
  AuthenticatedStaffCustomersRouteImport.update({
    id: '/staff/customers',
    path: '/staff/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffImportRoute =
  AuthenticatedStaffImportRouteImport.update({
    id: '/staff/import',
    path: '/staff/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffInvitesRoute =
  AuthenticatedStaffInvitesRouteImport.update({
    id: '/staff/invites',
    path: '/staff/invites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffProductsRoute =
  AuthenticatedStaffProductsRouteImport.update({
    id: '/staff/products',
    path: '/staff/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffSettingsRoute =
  AuthenticatedStaffSettingsRouteImport.update({
    id: '/staff/settings',
    path: '/staff/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffOrdersOrderIdRoute =
  AuthenticatedStaffOrdersOrderIdRouteImport.update({
    id: '/staff/orders/$orderId',
    path: '/staff/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/staff/categories': typeof AuthenticatedStaffCategoriesRoute
  '/staff/customers': typeof AuthenticatedStaffCustomersRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/invites': typeof AuthenticatedStaffInvitesRoute
  '/staff/products': typeof AuthenticatedStaffProductsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/staff/orders/$orderId': typeof AuthenticatedStaffOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/staff/categories': typeof AuthenticatedStaffCategoriesRoute
  '/staff/customers': typeof AuthenticatedStaffCustomersRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/invites': typeof AuthenticatedStaffInvitesRoute
  '/staff/products': typeof AuthenticatedStaffProductsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/staff/orders/$orderId': typeof AuthenticatedStaffOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/staff/categories': typeof AuthenticatedStaffCategoriesRoute
  '/_authenticated/staff/customers': typeof AuthenticatedStaffCustomersRoute
  '/_authenticated/staff/import': typeof AuthenticatedStaffImportRoute
  '/_authenticated/staff/invites': typeof AuthenticatedStaffInvitesRoute
  '/_authenticated/staff/products': typeof AuthenticatedStaffProductsRoute
  '/_authenticated/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/staff/orders/$orderId': typeof AuthenticatedStaffOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/reset-password'
    | '/catalog'
    | '/dashboard'
    | '/history'
    | '/invoices'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/orders/$orderId'
    | '/staff/categories'
    | '/staff/customers'
    | '/staff/import'
    | '/staff/invites'
    | '/staff/products'
    | '/staff/settings'
    | '/orders/'
    | '/staff/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/reset-password'
    | '/catalog'
    | '/dashboard'
    | '/history'
    | '/invoices'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/orders/$orderId'
    | '/staff/categories'
    | '/staff/customers'
    | '/staff/import'
    | '/staff/invites'
    | '/staff/products'
    | '/staff/settings'
    | '/orders'
    | '/staff/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/reset-password'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/invoices'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/staff/categories'
    | '/_authenticated/staff/customers'
    | '/_authenticated/staff/import'
    | '/_authenticated/staff/invites'
    | '/_authenticated/staff/products'
    | '/_authenticated/staff/settings'
    | '/_authenticated/orders/'
    | '/_authenticated/staff/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/categories': {
      id: '/_authenticated/staff/categories'
      path: '/staff/categories'
      fullPath: '/staff/categories'
      preLoaderRoute: typeof AuthenticatedStaffCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/customers': {
      id: '/_authenticated/staff/customers'
      path: '/staff/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof AuthenticatedStaffCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/import': {
      id: '/_authenticated/staff/import'
      path: '/staff/import'
      fullPath: '/staff/import'
      preLoaderRoute: typeof AuthenticatedStaffImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/invites': {
      id: '/_authenticated/staff/invites'
      path: '/staff/invites'
      fullPath: '/staff/invites'
      preLoaderRoute: typeof AuthenticatedStaffInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/products': {
      id: '/_authenticated/staff/products'
      path: '/staff/products'
      fullPath: '/staff/products'
      preLoaderRoute: typeof AuthenticatedStaffProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/settings': {
      id: '/_authenticated/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof AuthenticatedStaffSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/orders/$orderId': {
      id: '/_authenticated/staff/orders/$orderId'
      path: '/staff/orders/$orderId'
      fullPath: '/staff/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedStaffOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedStaffCategoriesRoute: typeof AuthenticatedStaffCategoriesRoute
  AuthenticatedStaffCustomersRoute: typeof AuthenticatedStaffCustomersRoute
  AuthenticatedStaffImportRoute: typeof AuthenticatedStaffImportRoute
  AuthenticatedStaffInvitesRoute: typeof AuthenticatedStaffInvitesRoute
  AuthenticatedStaffProductsRoute: typeof AuthenticatedStaffProductsRoute
  AuthenticatedStaffSettingsRoute: typeof AuthenticatedStaffSettingsRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedStaffOrdersOrderIdRoute: typeof AuthenticatedStaffOrdersOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedStaffCategoriesRoute: AuthenticatedStaffCategoriesRoute,
  AuthenticatedStaffCustomersRoute: AuthenticatedStaffCustomersRoute,
  AuthenticatedStaffImportRoute: AuthenticatedStaffImportRoute,
  AuthenticatedStaffInvitesRoute: AuthenticatedStaffInvitesRoute,
  AuthenticatedStaffProductsRoute: AuthenticatedStaffProductsRoute,
  AuthenticatedStaffSettingsRoute: AuthenticatedStaffSettingsRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedStaffOrdersOrderIdRoute: AuthenticatedStaffOrdersOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
